# Generated by Django 4.2.7 on 2026-06-08 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferred_langauge',
            field=models.CharField(default='English', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('citizen', 'Citizens'), ('worker', 'Worker'), ('officer', 'Officer'), ('admin', 'Admin')], default='citizen', max_length=10),
        ),
    ]
