# Generated by Django 4.2.7 on 2026-06-10 09:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaintID', models.CharField(blank=True, max_length=50, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('road', 'road'), ('water', 'water'), ('electricity', 'electricity'), ('sanitation', 'sanitation')], default='road', max_length=30)),
                ('address', models.CharField(max_length=300)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('image', models.ImageField(upload_to='complaint_image/')),
                ('status', models.CharField(choices=[('pending', 'pending'), ('assigned', 'assigned'), ('in_progress', 'in_progress'), ('resolved', 'resolved'), ('closed', 'closed')], default='pending', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'low'), ('medium', 'medium'), ('high', 'high'), ('emergency', 'emergency')], default='medium', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignedOfficer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints_assigned', to=settings.AUTH_USER_MODEL)),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaint_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
