# Generated by Django 4.2.7 on 2026-06-15 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0003_complaint_assignedworker_complaint_department_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='image',
            new_name='resolution_image',
        ),
        migrations.AddField(
            model_name='complaint',
            name='worker_notes',
            field=models.TextField(blank=True),
        ),
    ]
