# Generated by Django 4.2.7 on 2026-07-07 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0005_complaintsupport'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='support_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
